[build]
base = ""
command = "yarn build:prod"
publish = "public"

[build.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"
NODE_VERSION = "14"
GO_IMPORT_PATH = "github.com/spotlightpa/sourcesdb"
GO111MODULE = "on"

[context.deploy-preview]
command = "yarn build:stage"

[context.branch-deploy]
command = "yarn build:stage"


[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=1209600" # 2 weeks

[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" # 1 year

[[headers]]
for = "/js/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" # 1 year
